name: afran_project
description: Application pour le congrès AFRAN 2025

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  mongo_dart: ^0.9.1
  url_launcher: ^6.3.1
  video_player: ^2.8.3
  chewie: ^1.7.5
  youtube_player_iframe: ^5.2.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

executables:
  afran: main
  conference: conference_example 